services:
  - type: web
    name: learnix-ai-frontend
    env: node
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: npm run build
    startCommand: "npm start"
    envVars:
      - key: VITE_API_URL
        value: https://learnix-ai-backend.onrender.com
